version: '3.8'

services:
  app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DEBUG=False
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: